channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=24.2
- pip:
  - mlflow==2.21.1
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==5.9.8
  - scikit-learn==1.6.0
  - scipy==1.15.0
name: mlflow-env
